################################################################
#                                                              #
#                      < MagicSticks >                         #
#                                                              #
#                 Plugin created by Pulsi_                     #
#                For help join my discord!                     #
#              https://discord.gg/XMtFZvwXZG                   #
#                                                              #
################################################################

#Recive update messages if available
update_checker: true


################################################################
#                      < Projectiles >                         #
################################################################

#This is really Important, chose this to change the type of shoot style,
#by choosing <MANA>, you will use Experience for shoot cost, by choosing
#<AMMO>, you will use physic ammo for shoot, by choosing <MONEY>, you will
#use money for shoot
shoot_selector: AMMO

disable_fireball_explosion: true

disable_witherskull_explosion: true


################################################################
#                          < Mana >                            #
################################################################

#The delay for the Mana regeneration (in Ticks -> 20 = 1 Second)
mana_delay: 20

#The max amount of mana which a player can have
max_mana: 20

#The amount given to the player
mana_given: 1


################################################################
#                          < Ammo >                            #
################################################################

#The amount given to the player
bullets_gived_on_kill: 32


################################################################
#                          < Money >                            #
################################################################

#The delay for the Money regeneration (in Ticks -> 20 = 1 Second)
use_delay: true
money_delay: 20
money_given: 150

#The max amount of mana which a player can have
shoot_cost: 200

#The amount given to the player when he kill someone with a stick
eco_gived_on_kill: 2400

max_money: 5000


################################################################
#                       < Scoreboard >                         #
################################################################

use_scoreboard: true


################################################################
#                      < Death Drops >                         #
################################################################

#Used for upgrade your skills
drop_on_player_kill: true

#Drop the mob head and use it to increase your skills
drop_on_mob_kill: true

#See the config files for more info about custom drops

################################################################
#                        < Powers >                            #
################################################################

disable_power_drop: true

disable_more_powers_pickup: true


################################################################
#                        < Sticks >                            #
################################################################

disable_stick_drop: true

disable_more_sticks_pickup: true